USE [master]
GO

/****** Object:  Database [Student Affairs]    Script Date: 02/06/2022 11:23:09 ******/
DROP DATABASE [Student Affairs]
GO

/****** Object:  Database [Student Affairs]    Script Date: 02/06/2022 11:23:09 ******/
CREATE DATABASE [Student Affairs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Student Affairs', FILENAME = N'D:\devtools\MicrosoftSQL2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\Student Affairs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Student Affairs_log', FILENAME = N'D:\devtools\MicrosoftSQL2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\Student Affairs_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Student Affairs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Student Affairs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Student Affairs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Student Affairs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Student Affairs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Student Affairs] SET ARITHABORT OFF 
GO

ALTER DATABASE [Student Affairs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Student Affairs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Student Affairs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Student Affairs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Student Affairs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Student Affairs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Student Affairs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Student Affairs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Student Affairs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Student Affairs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Student Affairs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Student Affairs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Student Affairs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Student Affairs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Student Affairs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Student Affairs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Student Affairs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Student Affairs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Student Affairs] SET  MULTI_USER 
GO

ALTER DATABASE [Student Affairs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Student Affairs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Student Affairs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Student Affairs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Student Affairs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Student Affairs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Student Affairs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Student Affairs] SET  READ_WRITE 
GO

